name: CI DE DEPLOY

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
  
env:
    API_URL: ${{ secrets.API_URL }}
    API_KEY: ${{ secrets.API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
        
#      -
#        name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: m1nnemi/front
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#          
#      -
#        name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/front:latest

#      - 
#        name: Sleep for 30 seconds
#        run: sleep 30s
#        shell: bash 
       
      - 
        name: Executar Script Deploy do front para o portainer
        run: |
          URL=$API_URL
          API_KEY=$API_KEY
          FILE_PATH="docker-compose.yml"
          sudo apt-get install jq
          response=$(curl -s -X GET "$URL" -H "X-API-Key: $API_KEY" --insecure)
          
