name: CI/CD

on:
  push:
    branches: [ "develop" ]
  workflow_dispatch:
  
env:
    API_URL: ${{ secrets.API_URL }}
    API_KEY: ${{ secrets.API_KEY }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v3

#      -
#        name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
        
#      -
#        name: Docker meta
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: m1nnemi/front
#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
#      -
#        name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/front:latest
#      - 
#        name: Sleep for 10 seconds
#        run: sleep 10s
#        shell: bash 
      - 
        name: docker-compose
        run: |
            FILE_PATH="docker-compose.yml"
      - 
        name: Executar Script | deploy for portainer and VPC
        run: |
          chmod u+x index.sh
          ./index.sh
